### ISSUE TITLE
Save keyboard layout per sway window

### ISSUE THREAD

**Issue by MuratovAS** [Manjaro-Sway/manjaro-sway#122]
I propose to add to the [sway-xkb-switcher](https://github.com/nmukhachev/sway-xkb-switcher) distribution.
This package allows you to remember the keyboard layout for applications (for the session).
Pay attention, maybe it will be useful to users. 

- [ ] add xkb switcher to repo
- [ ] add xkb switcher to iso profile
- [ ] add xkb switcher as optional dependency to manjaro-sway-settings
- [ ] add xkb switcher optional startup to desktop settings

**Comment by boredland** [comment]
I saw that a lot for i3 and always wondered what the use-case on switching the layout per window is? I doesn't look hard to integrate and many seem to use it. I just fail to grasp the use-case for it. Is the idea that you have english in your editor and another layout for chatting on telegram f.e.?

**Comment by MuratovAS** [comment]
There are a large number of use scenarios.
This is especially true for people who use not English as the main one.
I say for myself.
Telegram and Firefox very often use in Russian. Programs for work Vscode, Kitty is always in English.
Often, work is interrupted by messages that require a change in the language. It happens to change the language of 3+ times per minute, with switched between applications.
It is possible to keep the language in the application saves a lot of time.

**Comment by boredland** [comment]
then this sounds like a great improvement. I am very lazy and if I am typing german, I just ignore the Umlauts 🇩🇪 🥳

**Comment by FallenChromium** [comment]
As a user of 4 input methods I can say that this may seem like a great improvement at first, but it is confusing sometimes (I've used an identical functionality in GNOME), especially it will be confusing as a default behavior. I think that we shall document on how to install it and probably help it somehow with a separate package or some defaults set, but it should be an opt-in rather than an opt-out experience. 
Btw @boredland, because German and english layout are somewhat similar you could use a compose key for Umlauts, [something like that](https://askubuntu.com/questions/1274176/how-to-access-keyboard-preferences-activate-the-compose-key-insert-german-um). I used that when I was trying to learn German 😃

**Comment by FallenChromium** [comment]
I think this is beyond the scope of the distro because it's very specialized. A PR to the documentation section on how to do it is welcome, @boredland, what do you think about closing this issue?

**Comment by MuratovAS** [comment]
> I think this is beyond the scope of the distro because it's very specialized. A PR to the documentation section on how to do it is welcome, @boredland, what do you think about closing this issue?

I think this is a rational decision
