### ISSUE TITLE
Move manjaro-sway-settings to different package name?

### ISSUE THREAD

**Issue by skunkfox** [Manjaro-Sway/manjaro-sway#126]
I love this version of Manjaro Sway. It's by far the best OS I've used (and I've used a lot). However one issue that I've run into time and time again is performing an upgrade and then seeing the beautiful theme revert back to something much uglier.

The problem seems to be that the name manjaro-sway-settings is used as both a local package (version 4.3.2-5) and a different package in the community repo (version 1.0.0-1). If I perform 'pacman -Syyuu', the correct package gets purged and the community package gets installed. This was incredibly confusing to me until I realized what was happening.

I know work is being done to get the maintainer's PGP properly signed and integrated into the Manjaro package pipeline, so perhaps the plan is to eventually replace the repo version of manjaro-sway-settings with the 4.3.2-5 edition. But as far as I can tell the 4.3.2-5 edition is 'heavier' and includes theming for more resource-hungry software like kitty, and may be inappropriate for lighter systems. (I could be wrong about this, if so please let me know.)

Would it make more sense to create a separate package, like manjaro-sway-settings-heavy or manjaro-sway-settings-x64 or something to that effect? I feel like the inability to perform 'pacman -Syyuu' is a bit of a landmine (I usually do use 'pacman -Syyu' but some tutorials suggest the former and many users don't know the difference).

**Comment by FallenChromium** [comment]
First things first: the version of manjaro-sway-settings you're using is kind of outdated, I can see why, you wasn't able to update it for a while 😄 

Second: If you like being on the bleeding edge, it's possible to install `manjaro-sway-settings-git` - it doesn't conflict with the package in Manjaro repos, is provided by us and will replace manjaro-sway-settings. I personally use it this way

Third: If getting the latest changes isn't for you (though almost every pull request almost immediately results in a release, so no big difference), it is possible to fix your problem. You can either do `sudo pacman -S manjaro-sway/manjaro-sway-settings` to explicitly install it from our repos, or you can move [manjaro-sway] repository in the `/etc/pacman.conf` to be defined earlier than community, to get updates from our repository by default. In the meantime I hope this distro will soon go official and this problem will be a thing of the past, because I also love that distro :)

**Comment by FallenChromium** [comment]
@boredland, is there a way to move`[manjaro-sway]` repo to the position higher than `[community]`? That could fix the problem until the flavor will become official and manjaro-sway-settings will get updated accordingly. By the way, is there an issue or a discussion where it's possible to check the progress on becoming "official"?

**Comment by boredland** [comment]
1. Changing the order of repos:

Afaik that's baked into the build-iso tool and probably would be needed to be baked in there. Honestly I don't get why it's not prioritizing the specific repo over the the custom. Perhaps @philmmanjaro can tell us if a PR changing that would have chances to get merged.

2. "Getting official". Imo there is no such thing. There is "being listed", there is "pushing packages to the official repos". For the second I am waiting for a word from @philmmanjaro telling me that my pgp key became part of the keychain package. As soon as that has happened, afaik, I can request "boxit" access to upload them ~directly to repos.
