### ISSUE TITLE
default workspaces on new monitors

### ISSUE THREAD

**Issue by FallenChromium** [manjaro-sway/manjaro-sway#127]
One of the painpoints in the default configuration of Sway is the way multi-monitor setups are behaving:
1. Workspaces are per-output, not merged into one area made of all connected displays (I don't advocate to set it up like this, but that's one of the solutions)
2. New workspaces aren't created when new display is connected = when you call existing workspace and you focus on the newly connected screen, the behavior may be different, see p.3:
3. When you call a workspace which doesn't exist, it is created on the currently focused output, but if you call an existing one, you aren't bringing it to the currently focused output, you're changing the workspace on the output it was initially created on = there's no way to "move" workspaces between the screens.

All in all it confuses me a lot, and while it's not the worst setup of course, I think there's a better way we can do this:
1. External tool: [swaysome](https://git.hya.sk/skia/swaysome)
2. Some sort of default setup to create additional workspaces for new monitors, maybe integrated with kanshi: [example](https://github.com/swaywm/sway/issues/4771#issuecomment-565674388), [kanshi reference](https://github.com/emersion/kanshi/blob/master/kanshi.5.scd#profile-directives)
3. I didn't research the question thoroughly yet: anyone having experience with multimonitor setups, or maybe some ideas?

**Comment by boredland** [comment]
swaysome looks like a great help. did you have a chance to look into it yet? should I add it to our repo?

**Comment by boredland** [comment]
1. we should ask the maintainer to make a tagged release
2. we should ask the maintainer to add a license

**Comment by Hyask** [comment]
Hi! Developer of `swaysome` here.  
I just found this issue, which is nice, because it seems I'm not the only one trying to solve the multi-monitor `sway` problem :)  
As you needed it, and I agree it was missing, I just pushed a license and a first release tag.  
Do you need anything else to help package `swaysome`? I do not use Manjaro personally on a desktop, so I'm not very used to its ecosystem, but I'll be happy to help if you need anything. Do you think it would help you if the repo was more accessible, on gitlab.com or github.com for example?

**Comment by FallenChromium** [comment]
Hello :D
Your project is very interesting, I appreciate the effort a lot ;)
One of the questions that I've had about `swaysome` is its' compatibility with `sworkstyle` - a Rust app which changes the workspace name dynamically depending on which apps are opened on the desktop itself. As far as I understand (didn't have any experience with Rust before), `swaysome` uses workspace names rather than `workspace number` functionality of Sway. If there's a way to add support for `workspace number <something>`, it will be awesome, because then the workspace names will remain stylish and informative, and user will be able to change it as wanted :)

Example of how that looks now:
![image](https://user-images.githubusercontent.com/43214067/132219365-839f46f8-7163-4d3a-8900-f3fa77bc91eb.png)

**Comment by Hyask** [comment]
Indeed, it uses the workspace names rather roughly. Since there seems to be some interest for the project, I've dug up the code and am working in cleaning it a bit to get better argument parsing, better logging, and then I'll see what can be done to make it compatible with `sworkstyle`. I may even look into `cargo publish` so that it could become available with `cargo install swaysome`.

**Comment by Hyask** [comment]
I've just pushed a 1.1.0 tag that includes many code rework and the compatibility with `sworkstyle` (awesome gadget, btw!). I still need to see how `cargo publish` works, but in the meantime, this should be a nicer `swaysome` release to build upon.

**Comment by boredland** [comment]
[bumped](https://github.com/Manjaro-Sway/swaysome/releases/tag/1.1.0-0) to the tagged version

**Comment by xeruf** [comment]
Interesting, I like the default behavior because it allows me to easily switch between monitors without needing a mouse or extra shortcuts. And then supplement it with https://github.com/manjaro-sway/manjaro-sway/issues/481

**Comment by boredland** [comment]
While I think swaysome still makes sense, I don't see us adding it to the default setup.
