### ISSUE TITLE
waybar fonts issue

### ISSUE THREAD

**Issue by andrius** [Manjaro-Sway/manjaro-sway#130]
After the update I receive this. Have been tried to reset setings/use from .skel/reinstall waybar
![image](https://user-images.githubusercontent.com/26776/127820549-bee688c4-1ca1-45a3-a7c9-f9adf296a0be.png)

**Comment by FallenChromium** [comment]
Do you have nerd-fonts-roboto-mono installed?

**Comment by FallenChromium** [comment]
I can see that it's not the latest config, because you have microphone percentage enabled and it was removed yesterday. Can you update your manjaro-sway-settings to the latest version and then exec `cp -rf /etc/skel/config/* ~/.config/` as suggested by the post-install hint? Make a backup, because it could replace some of files you've modified

**Comment by andrius** [comment]
I did that already and that `cp` does not replaced my files. css was updated while `~/.config/waybar/config` is not. Now I've fixed it. `rsync` is much reliable vs `cp`

**Comment by FallenChromium** [comment]
So, is the issue with icons resolved?

**Comment by andrius** [comment]
yes
