### ISSUE TITLE
How to return old screenshot menus?

### ISSUE THREAD

**Issue by andrius** [Manjaro-Sway/manjaro-sway#131]
- I need to take area screenshots often, i.e. to paste data to the slack;
- I do not have Print key on my bluetooth keyboard;

**Comment by FallenChromium** [comment]
Hello! While it is possible to return the old screenshot menu, in my opinion the better solution for you might be to adapt the current one:
1. Screenshot areas are working just fine, Print + P (pick) may look like a window chooser, but if you'll drag the cursor like usual, you will be able to choose a random area
2. As for the print key, adding the code below to `~/.config/sway/config.d/01-screenshots.conf`, for example, may resolve your problem with the hotkey.
```
$undbindsym Print
$bindsym $mod+shift+s mode $mode_screenshot
```

**Comment by FallenChromium** [comment]
As I said, it is possible (though I definitely don't advise) to go back to the previous mode. I'll just leave this info in case someone wants to do that and will close the issue.
Steps:
1. check the skel/etc/sway/modes/screenshot file from the older state, before the commit that changes screenshot mode, copy it over to the `~/.config/sway/config.d/screenshot`, for example. Give a different name to the mode (because it will conflict with the current one)
2. In any file in the `~/.config/sway/config.d`, declare a bind to use that mode, i.e `$bindsym $mod+shift+s mode <the_name_you_chose>`
