### ISSUE TITLE
Mode proposal + code: Screenshot mode

### ISSUE THREAD

**Issue by Zeioth** [Manjaro-Sway/manjaro-sway#162]
I wrote a new screenshot mode that uses sway shot instead of grimshot. The adventage is that you can easily upload to the cloud.

screenshot mode:

```
set $mode_screenshot "\
<span foreground='$waybar_secondary_color'></span>  \
<span foreground='$waybar_primary_color'> \
<span foreground='$waybar_secondary_color'>(<b>s</b>)</span>screen-up \
<span foreground='$waybar_secondary_color'>(<b>r</b>)</span>region-up \
<span foreground='$waybar_secondary_color'>(<b>w</b>)</span>window-up \
<span foreground='$waybar_secondary_color'>(<b>a</b>)</span>screen \
<span foreground='$waybar_secondary_color'>(<b>b</b>)</span>region \
<span foreground='$waybar_secondary_color'>(<b>c</b>)</span>window \
</span>"
mode --pango_markup $mode_screenshot {

    # Screen (upload)
    $bindsym s mode "default", exec swayshot display upload

    # Region (upload)
    $bindsym r mode "default", exec swayshot region upload

    # Window (upload)
    $bindsym w mode "default", exec swayshot window upload


    # Screen (local)
    $bindsym a mode "default", exec swayshot

    # Region (local)
    $bindsym b mode "default", exec swayshot region

    # Window (local)
    $bindsym c mode "default", exec swayshot window


    # Return to default mode.
    $bindsym Escape mode "default"
}

```

Screenshot
![20211001_154327](https://user-images.githubusercontent.com/3357792/135630533-9d5faa1f-2951-4c44-acf5-244ae3b9207e.jpg)

**Comment by boredland** [comment]
did you already try the [SWAYSHOT_WL_COPY_FILE](https://gitlab.com/radio_rogal/swayshot#path-to-last-screenshot) behaviour? does that save and wl-copy the file? I currently do not really upload the files directly but use the current setup to get it into clipboard only and paste it in github/gitlab/slack. Seems using SWAYSHOT_WL_COPY_FILE that should still work, but I think we should offer the file (as in filesystem) in addition. Otherwise this seems to be very similar anyway. Would be happy to give it a try.

**Comment by Zeioth** [comment]
It does both! 

* **3 keybindings to upload screenshots (screen, window, region)** → Take the screenshot, uploads it, copy the url to the clipboars, and sends a notification to the user.
 * **3 keybindings for local screenshots (screen, window, region)** → Works exactly the same, but the image is saved in the user images directory, instead of uploading.
