### ISSUE TITLE
nvidia support

### ISSUE THREAD

**Issue by mdesson** [Manjaro-Sway/manjaro-sway#165]
I am trying to install manjaro sway edition following the instructions (downloaded both files and `cat`'d them together). I selected open source drivers on the live iso. When boots off of the usb key the CPU remains at 98% or 99% consistently.

I'm unable to install as it is so slow it has difficulty picking up key presses accurately (it will interpret a single key down as several, making it nearly impossible to log into wifi).

**Version**: Latest release (202110130235)
**CPU**: i7-6700
**GPU**: RTX 3070
**RAM**: 16GB

![20211013_084028](https://user-images.githubusercontent.com/25888319/137136997-ea274a4d-7234-437a-b74e-8ebcc8d36588.jpg)

**Comment by boredland** [comment]
So I think/guess that nvidia open source drivers still don't play well with sway (see our readme) and it is falling back to strange CPU based renders or sth. like that. The proprietary drivers seem to work better recently, but I did not confirm that myself and due to a lack of Nvidia GPU wont be able to confirm that. What I can confirm: the current image works as expected in a Gnome Boxes VM.

**Comment by boredland** [comment]
While I don't think there is a lot we can do here "downstream" i think we could and should keep this thread open, since you won't be the last running into it.
