### ISSUE TITLE
[Question] Install manjaro-sway on top of existing install

### ISSUE THREAD

**Issue by kishikaisei** [Manjaro-Sway/manjaro-sway#249]
If I am running, for instance, Manjaro KDE, and I want manjaro with these configs et al. Is there away to do so?
(I tried to Install plasma second, but it is running to issues for me, and I am not proficient enough to figure it out)

**Comment by Mathew-D** [comment]
You might be able to do this by installing the manjaro-sway-settings package.  To do this you would need to add:
```
[manjaro-sway]
SigLevel = Optional TrustAll DatabaseOptional
#SigLevel = PackageRequired
Server = https://packages.manjaro-sway.download/$arch
```

To your "/etc/pacman.conf" file so that you can access all the packages that used in our settings package.  Afterwards you would also need to:
`cp -rf /etc/skel/.config/* ~/.config`
to setup our configs for your user that is using sway. 

Please note I haven't tried this so it might brake something but I think it will work.

**Comment by simon-bueler** [comment]
Closing this issue, feel free to reopen when there is still an issue.
