### ISSUE TITLE
image previews in ranger don't work

### ISSUE THREAD

**Issue by boredland** [Manjaro-Sway/manjaro-sway#29]

**Comment by simon-bueler** [comment]
could be just due to the terminal client, trying the same with alacritty or kitty should verify

**Comment by dbarronoss** [comment]
Works for me in kitty.

**Comment by boredland** [comment]
i the arm edition using termite? I thought so. And they have ranger + ueberzug too :/

**Comment by simon-bueler** [comment]
As far as I understood the maintainer of the arm version it does not work there: https://forum.manjaro.org/t/sway-community-edition-preview/48044/12
So we should probably switch the terminal program since we are not having the same hw limitations.
For me using alacritty or kitty is fine. I personaly use kitty because I got used to it.

**Comment by boredland** [comment]
fixed by adding and preferring kitty
