### ISSUE TITLE
disable the keyboard module in calamares

### ISSUE THREAD

**Issue by boredland** [manjaro-sway/manjaro-sway#317]
As it suggests that it does anything. But our keyboard settings are being done in sway only.

**Comment by AdriandMartin** [comment]
There is no need to do so. I recently discovered that Garuda gets Sway to use the chosen keyboard layout in Calamares during the system installation. The solution can be found in [their */etc/skel/.config/sway/config.d/input* file](https://gitlab.com/garuda-linux/themes-and-settings/settings/garuda-sway-settings/-/blob/master/etc/skel/.config/sway/config.d/input)

Although I tried, I couldn't adapt it as well as I wanted, so I will summarize my two attempts here in case someone could help me

## Direct adoption

The most direct adoption of that configuration might be to create a file */etc/sway/config.d/91-set-keyboard-layout.conf* which contains the following:
```sh
# Taken from https://gitlab.com/garuda-linux/themes-and-settings/settings/garuda-sway-settings/-/blob/bd685c5f8a6c2fcda54de73dcbfe0dee86c59046/etc/skel/.config/sway/config.d/input#L17

# set the keyboard layout specified during system installation
exec_always {
   'swaymsg input type:keyboard xkb_layout "$(localectl status | grep "X11 Layout" | sed -e "s/^.*X11 Layout://")"'
   'swaymsg input type:keyboard xkb_variant "$(localectl status | grep "X11 Variant" | sed -e "s/^.*X11 Variant://")"'
}
```
The problem I found is that, after copying it and reconfiguring Sway, I couldn't override the keyboard layout using a script into *~/.config/sway/config.d*. Taking into consideration the order in which the configuration is loaded, it should not happen, because the user's configuration is interpreted after the system's one, so I got stuck here

## My propose

To make it possible to override the system configuration (I know it's an important point of the distro's philosophy), I tried to adapt the configuration using Sway variables instead of the *exec_always* sentece, as it can be seen [in this commit](https://github.com/AdriandMartin/desktop-settings/commit/9e76392c16750823e8b4b09c8709a4cf6ab1eea2) in my fork of *desktop-settings*. Then, if the user wants to override the keyboard layout, just has to reassign the value of the variables using a script into *~/.config/sway/definitions.d*

However, I wasn't able to store the standard output of the command in a Sway variable (and I don't know if that's either possible), so although I've checked that the variable's value is correct, using `swaymsg 'exec "echo $keyboard_layout > foo"'`, it's not replaced as expected when it's used in the */etc/sway/input/default-keyboard* file, causing a parsing error

**Comment by boredland** [comment]
hm, perhaps we should use this to write the config file once at boot.

**Comment by AdriandMartin** [comment]
Yes, that sounds good. Could it be done using *exec* instead of *exec_always* in a script into */etc/sway/config.d*?

**Comment by boredland** [comment]
another idea:
have a little script that runs both of the command if no file .config/sway/config.d/00-keyboard.conf exists?

**Comment by boredland** [comment]
would appreciate your feedback!
https://github.com/manjaro-sway/desktop-settings/pull/132

**Comment by AdriandMartin** [comment]
I was just looking at the SUPPORT file, looking for the file name, and it wouldn't have to be updated anything with what you propose. Moreover you adjust the variant depending on it exists, so It seems to be a complete solution, looks fine :)

**Comment by AdriandMartin** [comment]
Well, I just saw that, in order to make it compatible with SUPPORT.md, the file *XX-keyboard.conf.example* should not be renamed. Other than that, everything seems fine

**Comment by boredland** [comment]
closing this, as this alternative approach fits the bill imo.
