### ISSUE TITLE
Zip larger than iso

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#319]
For the latest commits, the zip is larger than the actual iso, does it include something extra? Otherwise it seems superfluous to host it, maybe you could switch to an alternate compression method or isos are already compressed in a way that doesn't benefit from compression...

**Comment by boredland** [comment]
Are you referring to
[manjaro-sway-21.3.2-220905-linux515.iso](https://manjaro-sway.download/manjaro-sway/manjaro-sway-21.3.2-220905-linux515.iso) (1.89 GB)

vs

[manjaro-sway-21.3.2-220905-linux519.iso.zip](https://manjaro-sway.download/manjaro-sway/manjaro-sway-21.3.2-220905-linux519.iso.zip) (1.94 GB)

?

Those are two different images. Apparently the zipped image is slightly bigger before zipping and since afaik the limit for releases is 2000MB, we need to zip it. It is sad, but I don't see another way.

**Comment by boredland** [comment]
I guess this is clarified. If you have further questions.

**Comment by xeruf** [comment]
ah, I did not see the distinction, thanks

**Comment by boredland** [comment]
Ya, and perhaps the images were not distinct enough. 

I think we can go with two different images in the future:

- a conservative one with lts kernel, stable/old packages
- a bleeding edge/arch style one with stable kernel, unstable/latest packages

I personally don't see a lot of benefits through manjaros two weeks QA-Funnel for the "stable" packages - there may be on other distros with a lot of moving parts, like Gnome and KDE, where QA makes sense. Since nearly all sway-specific packages are not part of this funnel, I think for us the "stable" funnel is mostly pointless. As anecdotal evidence goes: I have been using Manjaro Sway with "unstable" repos on all kinds of machines and other then being annoyed sometimes by the amount of updates, I never had big issues (or: bigger issues then on my 'stable' machine).

**Comment by boredland** [comment]
As I see it, github pages does not have the same limitations regarding size as github releases.

 I am currently experimenting with uploading the unzipped iso there and I am going to rename "unstable" to "latest", as I don't like the semantics of it being "unstable".

**Comment by boredland** [comment]
Can't believe this just worked, but you can find the [latest iso always on our page now](https://manjaro-sway.download/) without need to extract etc.
