### ISSUE TITLE
Changing keyboard layout in Manjaro Linux Installer does not work

### ISSUE THREAD

**Issue by jnslmk** [Manjaro-Sway/manjaro-sway#36]
I've connected a generic German 105 key keyboard and tried to set this keyboard layout during install.

The installer lets me select the correct layout and displays the correct layout image. However, in the line edit to check the keyboard layout, it falls back to the default English keyboard layout.

When going back to the `Keyboard` step of the installer, the previously chosen layout is not selected anymore.

**Comment by boredland** [comment]
Hi there! if you proceed with the install, will the correct layout get applied anyways?

**Comment by boredland** [comment]
One workaround could be that you set the correct layout on boot... (at least I added some code for that to work)

**Comment by jnslmk** [comment]
Hi, thanks for the reply! I just tried selecting the correct layout on boot with release 202101161030. It results in the same error.

The problem persists in the other installation steps, e.g. when typing the username and is not applied to the installed system.

**Comment by boredland** [comment]
while the issue with calamares (the installer) ins't such an easy fix, the workaround with setting this in the boot menu seems to work for me with the latest image:
![Screenshot from 2021-01-18 22-20-29](https://user-images.githubusercontent.com/4662748/104963754-83dde780-59db-11eb-9fb7-5f749ca4ea96.png)

Just to explain: calamares updates the language settings. after the install, your selected language should be the default language of your system due to a little script I built in. BUT: updating the language "ad hoc" by calamares is a "X11"-Feature.

what we need to do here, is to update calamares to issue sth like 
```
swaymsg input type:keyboard xkb_layout de
```
whenever you change a language in the switcher. I don't see me doing that soon, but its definitely sth for the backlog.

**Comment by jnslmk** [comment]
Thank you for the explanation! Changing the boot setting works with the newest release for me too now

**Comment by k-dannemand** [comment]
i do not know if it is the same thing but when I set the keyboard layout to "International keyboard (with AltGr dead keys)" in the installer, then it is not set when I boot. i have fixed it myself by manually setting it in my sway config. but i do not see that the installer has set it anywhere.

just saying for the info :)

**Comment by boredland** [comment]
> "International keyboard (with AltGr dead keys)"

am I right in assuming that it doesn't set the variant, but the correct layout?

**Comment by k-dannemand** [comment]
@boredland 
yes it's correct, my bad. it's the US layout with the "altgr dead key" variant, that i try to set from the installer. just to make it clear:)

**Comment by boredland** [comment]
> yes it's correct, my bad. it's the US layout with the "altgr dead key" variant

Then my hopes are high that the workaround will apply soon.

**Comment by Birate** [comment]
I have a similiar issue with the keyboard layout. Even after changing it manually with the Manjaro Settings Panel, the layout still is locked to QWERTY.

**Comment by boredland** [comment]
> I have a similiar issue with the keyboard layout. Even after changing it manually with the Manjaro Settings Panel, the layout still is locked to QWERTY.

Ya, I think using the Manjaro settings panel will be a similar issue as with the calamares installer. It sets xdg values that don't translate into a sway config. If we want to support that to be changed "ad hoc" we probably should check if those values are set and override the sway config if it is. Don't know if that's worth the effort tho.

**Comment by Birate** [comment]
Thanks for the reply. Do you forsee any other kind of workaround to set keyboard for the a GUI/the installer, or is the next step to dive into the Calamares updater/manjaro-settings-panel to add a support for Sway _(Sorry fo the maybe dumb idea, new to sway)_

**Comment by boredland** [comment]
> Thanks for the reply. Do you forsee any other kind of workaround to set keyboard for the a GUI/the installer, or is the next step to dive into the Calamares updater/manjaro-settings-panel to add a support for Sway _(Sorry fo the maybe dumb idea, new to sway)_

I mean.. doesn't it work if you set it via Manjaro settings and reload sway? If so, that would be my proposed workaround :-D

**Comment by boredland** [comment]
I think I found a relatively easy solution to track the X11 changes and update sway accordingly:
https://github.com/Manjaro-Sway/manjaro-sway/issues/36

**Comment by Zeioth** [comment]
I installed the latest available ISO and I still found this problem.

The solution was to go to 

```
cd ~/.config/sway/config.d
```

In the file you find there, you can set the language on your keyboard. Then press win+shift+c to apply inmediately.

**Comment by adsick** [comment]
I've encountered same issue except I want to use Us Dvorak. Switching didn't worked so I stopped further installation

**Comment by adsick** [comment]
but why then the installer offers to pick layout?

**Comment by boredland** [comment]
Because that is the standard Manjaro installer. That works for all other Manjaro variants, but ours. If you're interested in getting into how to configure / recompile it more tailored to our needs, I'd be very open for contributions. Calamares itself seems to support configurations and extensions already, but I never figured out how they work (see: https://gitlab.manjaro.org/explore?utf8=%E2%9C%93&name=calamares&sort=latest_activity_desc)

**Comment by xeruf** [comment]
I do not understand how this issue is fixed. In the recent days I had to boot from a live stick multiple times to fix configuration oversights, manually changing the keytable to german is annoying, and remembering the english layout on a german keyboard is also annoying. How hard is it to create a custom ISO that has a different keyboard layout by default?

**Comment by boredland** [comment]
> create a custom ISO that has a different keyboard layout by default

while this would be certainly possible, this is not what this ticket is about. It is about the installer (calamares) setting the keyboard layout, which does work differently for us at sway than it does for any other distribution. It should be fairly easy to set up our own "keyboard" module in calamares though, I never saw this issue as sever enough and probably would just remove the keyboard module from calarmares in our version if I find the time.

**Comment by xeruf** [comment]
Sorry, I misphrased my question, see the edit now.
I intended to inquire about two things:
- whether there is any possibility to support what is set through calamares (since it is a ´swaymsg´ one-liner it should not be too hard, huh?)
- if it would be easy to fork a custom iso as workaround
