### ISSUE TITLE
Broken installer

### ISSUE THREAD

**Issue by pythonpro** [manjaro-sway/manjaro-sway#366]
The iso images' installer is broken for about 2-3 weeks already. I've checked every new release recently.
The error is the same (see attached photo).
![IMG_0419](https://user-images.githubusercontent.com/861363/203521305-0063f663-e2fa-4843-8fe8-eedabc7ed8f9.jpg)

**Comment by boredland** [comment]
that is bad. sounds like a dependency issue around calamares. will take a look on friday, I hope.

**Comment by eyes1971** [comment]
1. booting manjaro-sway-21.3.2-221120-linux515.iso
2. sudo nano /etc/calamares/modules/bootloader.conf
3. find efiBootLoader: "systemd-boot"
4. Setting efiBootLoader: "grub" 
5. save file & relogin 
6. start install manjaro 
7. end

**Comment by gegabo** [comment]
@eyes1971 how is it possible to relogin without login shell (assuming you are booting from an USB drive)?

**Comment by boredland** [comment]
Ah, so this may be just because I enabled systemd boot. Will go and revert that. Sorry for the inconveniences!

**Comment by boredland** [comment]
A new image got created. Some feedback would be great!

**Comment by gegabo** [comment]
Works perfectly for me! Thank you

**Comment by boredland** [comment]
Great! Sorry again for the hickups!

**Comment by pvlieres** [comment]
I can also confirm that the issue is gone. Thanks a lot for the quick fix!

**Comment by xeruf** [comment]
Just had this issue again with a two weeks old version, will check with the new version as well.

**Comment by varac** [comment]
I got the same error following https://github.com/manjaro-sway/manjaro-sway/issues/366#issuecomment-1326692880 (trying to use systemd-boot as bootloader), using `manjaro-sway-22.1.1-230515-linux61.iso`. Error log is here: http://termbin.com/yk12

**Comment by boredland** [comment]
Hm, I am not a great help there. I never got systemd-boot to work sadly. I you make any progress in that regard, I would be very eager to hear it!

**Comment by kstiehl** [comment]
@varac i've manjaro-sway running with systemd-boot. but it was quite hacky to come so far. its probably easier to switch after the installation. I remember that the directory inside `/tmp` is created during the installation. After some time the initalramdisk is downloaded but not the `/tmp/calamares` directory but to the `/` directory. After the vmlinuz files is downloaded and the ramdisk file is created in `/` you just have to do copy of the files whilst the installation is running. 

sorry for being a bit vague about it but i did it a few months ago. However it is still running since then.

Another thing to be carful about is that you need to make sure to have a /boot directory. It is actually not required for systemd-boot itself since it just requires the new /efi directory. however some pacman hooks that run during a kernel update work only with the /boot directory present. 

It was all very hacky to get it to work. so with all the knowledge i have today i would say it is a lot easier to download systemd boot. after the installation and change it afterwards. much easier

**Comment by varac** [comment]
Thanks @kstiehl, I managed to migrate to sd-boot+dracut after installation and documented the process [here](https://0xacab.org/varac-projects/doc/-/blob/main/systemd/systemd-boot.md#migrate-from-grubmkinitcpio-to-sd-bootdracut), for anybody interested in trying.
It would still be great if the installer would be fixed, or at least if the broken systemd-boot option would be removed (although I'd favor fixing it and making it the default :) but I guess this is more work).
