### ISSUE TITLE
swayr window change menu ($mod + p) not styled as other rofi menus

### ISSUE THREAD

**Issue by simon-bueler** [manjaro-sway/manjaro-sway#417]
So this should be seen as an improvement, as the general functionality is working fine.
The menu for swayr gets configured in /etc/xdg/swayr/config.toml and does not allow changes on execution.
Since we have the theming of rofi configured to be changed and all menus using execution time configuration of visuals, we have a problem there. 
Maybe @tsdh can help as the maintainer of swayr to provide functionality to help us out.

**Comment by boredland** [comment]
I guess we should start by first manually adapting the [config.toml](https://github.com/manjaro-sway/desktop-settings/blob/sway/community/sway/etc/xdg/swayr/config.toml) to our theme and then look for the configurability.

**Comment by tsdh** [comment]
Hey all, swayr author here.  I don't quite understand the issue, i.e., how swayr would mess with the theming of rofi and what "does not allow changes on execution" means. I would expect that rofi has its own config and possibly theme css file, at least that's what I know from wofi... :shrug:

**Comment by boredland** [comment]
Hi there! Thanks for stepping by! 

The (not so big) issue is the following:

at some point we decided to read theme colors from a common file, so we don't have to configure them on a per-application basis. for lots of tools, like rofi, you can pass those theme settings via a parameter, so that is not the issue per se. The actual problem is, that with swayr calling rofi directly, we have no proper place to set such a parameter from the sway config or similar. An ideal solution for my perspective would be, if we could pass the rofi command as a parameter. Alternatively we could update the userspace swayr configuration based on the theme configuration - an approach which has proven quite cumbersome in the past.

**Comment by boredland** [comment]
@simon-bueler I did go with the lightweight approach of generating `.config/rofi/config.rasi` based on the sway config and removed all the "parameter" passing. I can't recall why we added that back then and to me this just seems to be a cleaner solution overall.

it is on `manjaro-sway-settings-git` and I'd really like to hear your feedback!

**Comment by tsdh** [comment]
@boredland I agree that styling rofi with its own `config.rasi` sounds like a much better approach.

**Comment by simon-bueler** [comment]
Sometimes there is an easier solution than you think. Tried it and everything seems to work fine. Thanks @tsdh for passing by and @boredland for the improvement.
