### ISSUE TITLE
Out of date download page (link in readme)

### ISSUE THREAD

**Issue by Cs137** [manjaro-sway/manjaro-sway#432]
The first item of the readmes' [how to install](https://github.com/manjaro-sway/manjaro-sway#how-to-install) section refers to [manjaro-sway.download](https://manjaro-sway.download) in order to find the latest images.

The page is not up to date and lists `manjaro-sway-21.3.2-230116-linux515.iso` as latest image.

**Comment by Cs137** [comment]
My appologies, but I am quite puzzled. The one I mentioned is the latest release that is also listed [here](https://github.com/manjaro-sway/manjaro-sway/releases), but the file offered at *manjaro.org/download* corresponds to [`Manjaro-ARM-sway-generic-22.12.img`](https://github.com/manjaro-arm/generic-images/releases/download/22.12/Manjaro-ARM-sway-generic-22.12.img.xz).

**Comment by Cs137** [comment]
My appologies, the one I mentioned is the latest release that is also listed [here](https://github.com/manjaro-sway/manjaro-sway/releases), but the file offered at *manjaro.org/download* corresponds to [`Manjaro-ARM-sway-generic-22.12.img`](https://github.com/manjaro-arm/generic-images/releases/download/22.12/Manjaro-ARM-sway-generic-22.12.img.xz).

`22.12` vs. `21.3.2` caused the actual confusion on my side.

**Comment by boredland** [comment]
Manjaro still didn't update their version number inside [lsb_releases](https://gitlab.manjaro.org/packages/core/manjaro-release/-/raw/master/lsb-release), that's why our version is not updated still. perhaps @philmmanjaro wanted to look into it.

BUT: this repo is just for the x86 version of manjaro sway. For support regarding the ARM version, pls head over the manjaro [forum](https://forum.manjaro.org/).
