### ISSUE TITLE
top OS bar does not always appear

### ISSUE THREAD

**Issue by jahway603** [Manjaro-Sway/manjaro-sway#47]
Not sure if others are experiencing this, but after booting into SwayWM the top bar does not always appear. I have not been able to figure out why this is happening in order to try to fix it, so wanted to log the issue.

**Comment by JenSeReal** [comment]
I've experienced the same. Sometimes it would appear, sometimes not. But since I commented kanshi out of the auto start it opens all the time. Don't know if that is correlated, it would not make any sense. I needed to disable kanshi because sway would not start with kanshi activated and my ultrawide monitor set in the sway config

**Comment by boredland** [comment]
I think kanshi and the weird things I do to sideload into the waybar config are to blame. Perhaps I should just remove both.

**Comment by AbsenceFlintIvy** [comment]
I am having the same problem.

**Comment by boredland** [comment]
removed a lot of complicated stuff (kanshi, generating the waybar config), so this should work now.
