### ISSUE TITLE
🐛 regression of: custom timeouts definitions for idle related tasks (lock, display off, sleep) are ignored

### ISSUE THREAD

**Issue by bdefore** [manjaro-sway/manjaro-sway#801]
### branch

stable

### Architecture

x86_64

### Description

This follows up from https://github.com/manjaro-sway/manjaro-sway/issues/547 ... The updates related to this issue fixed it; my custom timeouts were used in the building of the `swayidle` parameters.

But after a fresh install of Manjaro Sway I noticed the desktop was sleeping again after an hour and the custom parameters were no longer being used, as verified by `ps aux | grep swayidle`

### Reproduction steps

My overrides live in $HOME/.config/sway/definitions.d/user_definitions.conf

First, I noticed `sleep_timeout` now seems to be split into `sleep_timeout_bat` and `sleep_timeout_ac` ... but renaming my local ones had no effect.

I notice that the /etc/sway/definitions calls /etc/sway/autostart right after defining them. And the local userspace overrides are loaded after /etc/sway/definitions within /etc/sway/config. The support doc mentions that you can disable anything in autostart by setting it to `""` but I don't want to disable `swayidle` just change its initializing parameters.

Ultimately I made a `~/.config/sway/definitions.d/autostart.conf`:

```
# sleep when yer dead
set $override_sleep_timeout_ac 99999999999999

set $swayidle swayidle -w \
    timeout $idle_timeout 'brightnessctl -s && brightnessctl set 10' \
    resume 'brightnessctl -r' \
    timeout $locking_timeout 'exec $locking' \
    timeout $screen_timeout '/usr/share/sway/scripts/keyboard-backlight-switch.sh off && swaymsg "output * dpms off"' \
    resume '/usr/share/sway/scripts/keyboard-backlight-switch.sh on && swaymsg "output * dpms on"' \
    timeout $sleep_timeout_bat '[ "$(acpi -b | grep Discharging)" != "" ] && systemctl suspend' \
    timeout $override_sleep_timeout_ac '[ "$(acpi -b | grep Discharging)" = "" ] && systemctl suspend' \
    before-sleep 'playerctl pause' \
    before-sleep 'exec $locking & sleep $sleep_delay' \
    after-resume '/usr/share/sway/scripts/keyboard-backlight-switch.sh on && swaymsg "output * dpms on" && brightnessctl -r'
```

But this is just copy pasting a large amount of code within Manjaro Sway that I'd rather not do.

Am I going about this right?

**Comment by trinitronx** [comment]
@bdefore:  I too have had the need to customize `swayidle` behavior.  I'm running Manjaro Sway on a Home Theater PC (HTPC), so the requirements are slightly different than a laptop.  For example:

- No keyboard brighness
- No concerns for battery vs AC power
- Display is an HDTV connected over HDMI, so it cannot sleep unless either:
  - HDMI output turns off & display automatically sleeps due to no signal (not ideal)
  - CEC command is sent over HDMI, telling the display to sleep (best, but sometimes buggy)
- I never want this HTPC to suspend... should be always on

To fulfill the requirements above, I overrode the definition of `$swayidle` and configured it like so:

<details><summary>Added config file: <code>~/.config/sway/definitions.d/01-override-swaylock.conf</code> (expand for contents)</summary>
<p>

```
set $locking swaylock --daemonize

#set $swaylock_time_kill_cmd pkill --full --signal 31  "nwg-wrapper -s swaylock-time.sh.*--sig_quit 31"
#set $swaylock_time_kill_cmd /home/trinitronx/bin/swaylock-time-hide.sh
#set $swaylock_time_start_cmd /home/trinitronx/bin/swaylock-time-show.sh


### Idle configuration
# This will lock your screen after 300 seconds of inactivity, then turn off
# your displays after another 300 seconds, and turn your screens back on when
# resumed. It will also lock your screen before your computer goes to sleep.
#
set $idle_timeout 240
set $locking_timeout 300
set $screen_timeout 600
set $sleep_timeout 900
set $sleep_delay 2

#set $systemctl_suspend 'systemctl suspend'
# Shell no-op to turn off suspend
set $systemctl_suspend :

set $swayidle swayidle -w -S seat0 \
    idlehint $idle_timeout \
    timeout $idle_timeout 'light -G > /tmp/brightness && light -S 10' resume 'light -S $([ -f /tmp/brightness ] && cat /tmp/brightness || echo 100%)' \
    timeout $locking_timeout 'exec $locking' \
    timeout $screen_timeout 'swaymsg "output * power off"' \
      resume 'swaymsg "output * power on"' \
    timeout $screen_timeout 'sudo pkill -USR2 cec-dpms' \
      resume 'sudo pkill -USR1 cec-dpms' \
    before-sleep 'playerctl pause' \
    before-sleep 'exec $locking & sleep $sleep_delay'
``` 

</p>
</details>

<details><summary>Add or modify local user configuration for Sway in file: <code>$XDG_CONFIG_HOME/sway/config</code></summary>
<p>

**Note:** This may not be necessary, but I wanted to ensure that my config always overrides Manjaro Sway's version.

```
# Default config for sway
#
# Copy this to ~/.config/sway/config and edit it to your liking.
#
# Read `man 5 sway` for a complete reference.

# styles - set the folder for your theme definition file
set $theme /usr/share/sway/themes/matcha-green

# theme variables
include $theme/definitions

# global variables
include /etc/sway/definitions

# user variables
include $HOME/.config/sway/definitions.d/*.conf

include /etc/sway/inputs/*
include /etc/sway/outputs/*

# enable modes
include /etc/sway/modes/*

# only enable this if every app you use is compatible with wayland
# xwayland disable

# include additional configs e.g. to autostart applications
include /etc/sway/config.d/*

# user config
include $HOME/.config/sway/config.d/*.conf

```

</p>
</details> 

This configuration has survived the many updates to `manjaro-sway-settings` package on my system. (Meanwhile, other things I had configured have broken over time and I have had to fix them)

I copied and edited the definition of `$swayidle` back before the change to using `$sleep_timeout_bat` and `$sleep_timeout_ac` that you mentioned, but it's not a problem for me because my HTPC is not a laptop and so I don't need to handle special cases for using battery power vs. AC.  The main thing I added was sending process signals to [`cec-dpms`][1] (which didn't originally work, so I have created a custom build for fixing & testing some things).  So, you can ignore that part if you don't need it.  In fact, you may choose to customize the `swayidle` invocation further based on your own system & unique requirements. :shrug: 


All this is to say:  **You're on the right track**!

Overriding `$swayidle` for your user is the way to go, and will allow you to customize things specific to your use case.  Meanwhile, the system-level configs in `/etc/sway` (installed & updated by `manjaro-sway-settings` package) can and probably will change out from under us continually).  At least by overriding `$swayidle` invocation completely, we insulate ourselves from such changes as variable names, etc...


Hope this helps!

[1]: https://github.com/trinitronx/cec-dpms

**Comment by boredland** [comment]
Ya, this honestly should be the preferred way of changing it.

**Comment by trinitronx** [comment]
@bdefore:  One more thing...

When configuring Sway, I've found it incredibly helpful to create a special "Sway Debug" Wayland Session that logs all `sway` executable's output to a file.  (It's now possible to pass args to Sway after manjaro-sway/desktop-settings#196, so pass `--verbose` and `--debug` for maximum log output)

For example:

<details><summary>Add file <code>/usr/share/wayland-sessions/sway-debug.desktop</code></summary>
<p>

```
[Desktop Entry]
Name=Sway DEBUG LOGGING
Comment=An i3-compatible Wayland compositor
Exec=sway --verbose --debug 1>/tmp/sway.log 2>&1
Type=Application

```

Then:

1. Logout and back in to the `Sway DEBUG LOGGING` session from your greeter
2. Change some Sway settings & configs
3. Press <kbd>$mod</kbd>+<kbd>Shift</kbd>+<kbd>c</kbd> (or run `swaymsg reload`)
4. Watch in `/tmp/sway.log` for what happens.

Paying attention to the order of operations for how Sway is loading config files, what variable definitions are being evaluated to, and what commands are run for a `bindsym` mapping, among other things can be immensely helpful!
Also the command output for commands bound via `bindsym` is output here, so you can even debug any custom commands you might be adding.
</p>
</details>



P.S.: I just realized that you _might be_ the same person who wrote a [controller profile mapping web app for the Saitek x52 H.O.T.A.S here][1] ... small world! :grinning: 
I've recently brought my old pre-Logitech version of that H.O.T.A.S. controller out of storage to play some KSP 1 with [this joystick controller mod][2] (a.k.a. [AdvancedFlyByWire-Linux][3] on `ckan`).

It turns out that there is a daemon included in [`nirenjan/libx52`][4] that enables usage of the Multi-Function Display, LED settings, as well as a mouse pointer support for the small "nub" thumbstick on the throttle unit.  Although, I turned that feature off so I could map it elsewhere in-game.

There is mention of support for [controller Profiles... but it's not fully implemented yet][5].  So, I was wondering about that profile creator web app and how it worked... and whether or not that could be used to help reverse-engineer the x52 profile format and how to create profiles using other apps (e.g. `libx52`).  I'm not entirely sure if that's feasible, or how the profiles support works yet either in Windows or Linux, but was curious to poke around the code to see what it's doing.


[1]: https://www.reddit.com/r/hotas/comments/gfzmlu/you_can_now_create_dcs_x52_pr0_files_from_your/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
[2]: https://forum.kerbalspaceprogram.com/topic/175359-112x-afbw-revived-joystick-controller-mod/
[3]: https://spacedock.info/mod/1870/AFBW%20Revived%20(Linux%20version)
[4]: https://github.com/nirenjan/libx52
[5]: https://github.com/nirenjan/libx52/blob/7a56af032b30dd2e0b9b032bd6d8ee607d53db45/daemon/x52d.conf#L95-L97

**Comment by boredland** [comment]
Hey! I configured the swayidle-service unit, that will pick up a configuration file, that helps configure the service. Added note [here](https://github.com/manjaro-sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-edit-the-swayidle-settings-sleeplock-etc) about it.
