### ISSUE TITLE
What should be the default launcher?

### ISSUE THREAD

**Issue by boredland** [Manjaro-Sway/manjaro-sway#82]
[sway-launcher-desktop](https://github.com/Biont/sway-launcher-desktop):

- fast
- fits into the "cli-applications" style
- does "one thing only" (launching)
- not very popular

[wofi](https://hg.sr.ht/~scoopta/wofi):

- not being actively maintained
- does "one thing only" (launching) but allows to display custom content too
- bit slow

[bemenu](https://github.com/Cloudef/bemenu):

- never tried

I am very open to other proposals and will add them to this issue. Polling is open until 2021-08-11.

[![](https://api.gh-polls.com/poll/01FAAJED1AA4HHR51MYT9WPH4G/sway-launcher-desktop)](https://api.gh-polls.com/poll/01FAAJED1AA4HHR51MYT9WPH4G/sway-launcher-desktop/vote)
[![](https://api.gh-polls.com/poll/01FAAJED1AA4HHR51MYT9WPH4G/wofi)](https://api.gh-polls.com/poll/01FAAJED1AA4HHR51MYT9WPH4G/wofi/vote)
[![](https://api.gh-polls.com/poll/01FAAJED1AA4HHR51MYT9WPH4G/bemenu)](https://api.gh-polls.com/poll/01FAAJED1AA4HHR51MYT9WPH4G/bemenu/vote)

**Comment by FallenChromium** [comment]
There is a reason to switch from Wofi, I believe, it is very, very slow at times to open up, the window rendering part takes about 0.5s to open up. 

I can advocate for bemenu because I have used it in my setup before switching to Manjaro Sway, it looks exactly like dmenu and is configured via command arguments, so you can fit it nicely with sway definitions to match the color scheme. It also matches the cli-applications style, because it looks like a terminal buffer popping up on top of your desktop. It is blazingly fast and does one thing only by default (launching apps), but can be used as dmenu, to show dialogs, execute interactive scripts, be used as a password manager etc.

**Comment by simon-bueler** [comment]
Why I would not favor sway-launcher-desktop is simply since it is shell script based and has problems handling .desktop files or launching applications. If you want to have a look at the available options see [here](https://github.com/swaywm/sway/wiki/Useful-add-ons-for-sway#launchers). 
I would recommend using a launcher that is stable, has a good support from community and maintainer and a performance oriented implementation.

**Comment by boredland** [comment]
> Why I would not favor sway-launcher-desktop is simply since it is shell script based and has problems handling .desktop files

I don't think that is a valid point. All launchers are parsing .deskop files and I think the issue with some in-compliant .desktop files is solved.

however: when looking at the stars of all those options, the top seem to be:

- ulauncher
- bemenu
- sway-launcher-desktop
- nwg-launchers

We once tried to migrate to ulauncher and faced severe issues we didn't overcome. Don't really remember @simon-bueler perhaps does though.

nwg-launcher in dmenu-mode either requires another tool that passes the list of applications to it or just uses only the current $PATH. This does not sound very compelling compared with sway-launcher-desktop. From the rest of that list, there definitely are compelling ones - but probably (yet) fail in the section of a bigger community. I think I perhaps will have a look at [fuzzel](https://codeberg.org/dnkl/fuzzel) since for me it looks like sway launcher desktop with icon support.

**Comment by boredland** [comment]
lil update: fuzzel as of no only supports .desktop files - I would argue that having sth. like nmtui in the launcher is nice enough to insist it showing the binaries from $PATH too.

**Comment by Mathew-D** [comment]
I know the projects goal is to be cli like and I hate to be one of those people, but I have been customizing most of my system to a more graphics look / mouse use.  And from that direction wofi is still the better looking one. The main thing I dislike about way-launcher-desktop is the lack of icon use from .desktop launches.

**Comment by boredland** [comment]
hm, I came from the i3 manjaro setup initially and havent missed desktop icons a second there. BUT: dnkl already mentions that he'd accept a PR that adds the $PATH binaries if its only the delta of those not already sourced from .desktop files.

**Comment by boredland** [comment]
bemenu has no option to open things in a terminal ref. https://github.com/Cloudef/bemenu/issues/43

**Comment by Mathew-D** [comment]
fuzzel has no mouse support.  https://codeberg.org/dnkl/fuzzel/issues/30

**Comment by FallenChromium** [comment]
Okay... For mouse support, icons, and drun functionality with CLI apps actually there's a [rofi fork that supports wayland.](https://github.com/lbonn/rofi). It exists on [AUR](https://aur.archlinux.org/packages/rofi-lbonn-wayland-git/) already. It's not ideal to use a fork which may in the future have problems with maintenance, but with all the requirements above I don't see any other option.

**Comment by Mathew-D** [comment]
The last update on that fork was 2020-09-07.   I hate to say it but changing to sway-launcher-desktop or staying with wofi might be the best choice.

**Comment by FallenChromium** [comment]
I believe it is not an option, because of how slow Wofi opens, besides, it blocks [this PR](https://github.com/Manjaro-Sway/desktop-settings/pull/18#issuecomment-881583473) to change the terminal to foot. I get your concerns though, being stuck with a launcher which may deliver problems in the future is not desirable. What about [Onagre](https://github.com/oknozor/onagre) then?

**Comment by Mathew-D** [comment]
First off, thank you for looking @FallenChromium.  I just tried onagre, it crashes loading htop which doesn't make it a good choice for the group and it no mouse support other then scrolling.  IF we must change it looks like sway-launcher-desktop has everything but icons.

**Comment by FallenChromium** [comment]
I've just tried to use sway-desktop-launcher with foot --server + footclient to drastically reduce rendering time, and it helped - it does feel snappier than Wofi, but there's a caveat - when binding footclient sway-launcher-desktop, you can open as much instances as you want, and also there's noticable fzf lag to populate the list. The other problem is that I cannot limit the number of items in the list to eliminate annoying list population "animation", the only workaround might be to create yet another window class and make a sway rule to make terminal small. 

Overall, it doesn't look bad, but definitely using a binary executable and not shell will contribute to a better experience. My final word is that I'd prefer rofi fork or fuzzel as the mainstream option, but the thing is, launcher is very easy to change anyway (basically a $menu redefine), so we should just choose the most stable and attractive one for those users that won't research and will use the stock one.

**Comment by boredland** [comment]
so lets at least add up all criteria we have. so we can determine a suitable candidate:

- list .desktop entries incl. icons
- list bins from $PATH
- execute terminal commands by defining a command (foot compatibility)
- fast
- mouse support
- solid community support

in my personal opinion mouse support isn't a necessity. if I am typing an application name already, why wouldn't I use arrow-key + enter to select the application I need.

same applies for .desktop files. I really liked dmenu-like launchers in the past and you barely need .desktop entries if you already have everything from $PATH.

**Comment by FallenChromium** [comment]
For the sake of demonstration I've tested some options and personally think that bemenu, while being extremely barebones, works the best. I've eliminated some unresponsiveness of wofi by deleting default config and launching it repeatedly, and on the video it's hard to tell the difference, but in a cold start sway-launcher-desktop and bemenu are way more responsive. GIF is slow specifically to show all the animations and time required by the launchers to load.
![clip](https://user-images.githubusercontent.com/43214067/126013186-da77a315-e0f3-4cac-960e-2b43e6160678.gif)

**Comment by Mathew-D** [comment]
Well I have been playing with the rofi fork that supports wayland that @FallenChromium listed and it seems to work well with foot.  I just had to put the following in the config file:
   terminal: "foot";
    run-shell-command: "{terminal} {cmd}";
Can @FallenChromium run some responsive tests on it to see how it compares as they should be run on the same system.

**Comment by FallenChromium** [comment]
After installing Linux 5.13 and doing some optimizations on my end for configs of every launcher, every single one of them opens fast enough, with bemenu being the fastest but also the most inconvenient because of the lack of history and icons. I can't upload a new gif because I would have to shrink the resolution too much, and I think it's better to make these tests objective. Do I have any way to measure window rendering time, some kind of benchmark or a backtrace tool?

Regarding lbonn's rofi fork - I've also liked it, because it's very configurable and flexible (we can configure console apps launch command to eliminate the problem with foot, as @Mathew-D said) , and, while not feeling very fast still is snappier than wofi. And also, the codebase is actually fresh, because it's in-line with latest rofi release anyway. The only question then is where to find matcha-green theme for rofi, but if we will integrate wpgtk it won't be a problem, as it has a template for rofi.
