### ISSUE TITLE
🐛 Extremely high CPU usage by swaylock-effects

### ISSUE THREAD

**Issue by hakanyi** [manjaro-sway/manjaro-sway#867]
### branch

testing

### Architecture

x86_64

### Description

Anybody else experiencing high CPU usage by swaylock-effects? 
Any pointers as to how to log/debug this? 
Running sway 1.10-1 on Manjaro kernel 6.6.59 (same with 6.10.14; 6.11 is not usable for me due to wake-from-suspend issues)
![image](https://github.com/user-attachments/assets/d6516145-5aed-49b2-8c6e-4bad08851daf)

### Reproduction steps

```bash
Run sway as usual, observe high CPU usage as described above
```

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Add a new FAQ entry in SUPPORT.md to address the issue of high CPU usage by swaylock-effects and provide troubleshooting steps.

I also created pull request: https://github.com/manjaro-sway/manjaro-sway/pull/868


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by boredland** [comment]
I guess there is an upstream issue already: https://github.com/mortie/swaylock-effects/issues/109

Does disabling the screenshot feature work for you?

**Comment by boredland** [comment]
No reaction, no support.

**Comment by hakanyi** [comment]
Sorry -- hasn't happened since the most recent updates on testing came through. I'll re-open if it happens again
