### ISSUE TITLE
suspend & lock

### ISSUE THREAD

**Issue by andrius** [Manjaro-Sway/manjaro-sway#89]
When I close a laptop lid, it suspends, but the WM session get opened and next time I can just continue working, without entering password.

Desired behavior is to get suspend together with screen lock.

**Comment by FallenChromium** [comment]
Can't confirm that, I've installed my OS 3 days ago, my installation locks up as soon as I close the lid. Did you update the packages and updated the skel, as it is instructed in the readme?

**Comment by Mathew-D** [comment]
Make sure the package swayidle is installed.  In one of the old images it wasn't installed by default.

**Comment by andrius** [comment]
Yes, now it works! swayidle wasn't there

**Comment by FallenChromium** [comment]
Actually... I've experienced other kind of problem with suspend and lock. Suspending and locking my laptop without external display works just fine, but using an external display, after waking up external display is unlocked, and after a click on it, laptop's display gets freed from the lockscreen too. A weird bug, but a serious one, because privacy is a thing we should all expect and rely on when using our computers

**Comment by boredland** [comment]
that indeed sounds strange.

**Comment by Mathew-D** [comment]
if you manually start the lock does it do the same thing?

**Comment by FallenChromium** [comment]
While manually locking the screen it does not occur. I should say that I couldn't reproduce it again. Maybe it's because my laptop have stayed in the sleep mode for about 3-4 hours back then, and now I'm testing it almost immediately after pressing suspend. If I will encounter it again, I'll let you know

**Comment by andrius** [comment]
I can confirm this issue and can recreate (with the external display).

The workflow:
- you work with external display connected;
- disconnect hdmi, closing lid (laptop suspends);
- another time I open the laptop (wakeup); connect the external display and for a moment can see my screen unlocked

**Comment by FallenChromium** [comment]
Can't reproduce this anymore, please reopen if you'll encounter with lockscreen vanishing again.
