### ISSUE TITLE
Firefox already inhibits sleep through GTK

### ISSUE THREAD

**Issue by FallenChromium** [Manjaro-Sway/manjaro-sway#97]
As far as I am aware, Firefox already inhibits sleep when playing videos, for example, and it was very confusing to me to see my laptop not going to sleep by default when firefox is opened, even when there's only a new tab. Maybe it's worth it to change the default behavior, so it will be more predictable?

Edit: in the config there's `for_window [app_id="firefox"] inhibit_idle fullscreen`, but apparently "fullscreen" is also when it's the only app on the desktop?

**Comment by boredland** [comment]
> Edit: in the config there's `for_window [app_id="firefox"] inhibit_idle fullscreen`, but apparently "fullscreen" is also when it's the only app on the desktop?
> 

While I am not the biggest Firefox user, I think I saw that behaviour myself some time ago.

The [docs](https://man.archlinux.org/man/sway.5.html) seem to back this:

> fullscreen will inhibit idle when the view is fullscreen (or a descendant of a fullscreen container) and is visible

However: I think client side inhibit did not work earlier. Perhaps it works now due to this systemd unit being added in the arch container? https://github.com/archlinux/svntogit-community/blob/packages/sway/trunk/50-systemd-user.conf
